### ISSUE TITLE
Extra space added when using the javalang:string-writer writer.

### ISSUE THREAD

**Issue by leukim** [walkmod/walkmod-core#56]
After running a dead-code-cleaner with no real changes, I see that some formatting has been altered unnecessarily, as in the case:
`names.entrySet().stream().map(Map.Entry::getValue).collect(Collectors.toList());`
to
`names.entrySet().stream().map(        Map.Entry::getValue).collect(Collectors.toList());`

Adding some extra space (8 spaces) before Map.Entry that should not be there.

**Comment by jordiponsllaurado** [comment]
I have the same issue

**Comment by rpau** [comment]
Ok, I am going to test it and figure out what is happening.  Formatting issues are complicated, but I will try to fix it during this week.

Thanks for reporting it.

**Comment by rpau** [comment]
Fixed at walkmod-javalang-plugin, commit 9e88432fa579915c5d7508f4fc014197df2372fe
