### ISSUE TITLE
Running walkmod in the whole Android project

### ISSUE THREAD

**Issue by luiscruz** [walkmod/walkmod-core#59]
When I run walkmod with a basic Android project, it creates 2 ```walkmod.xml``` files:

```
./walkmod.xml
./app/walkmod.xml
```

If I apply walkmod in the root, it will not apply to the whole project. How can I apply walkmod with a single configuration to whole project?

**Comment by luiscruz** [comment]
If it helps, I've tried with this very simple Android application:

https://github.com/luiscruz/blank-app

**Comment by rpau** [comment]
Hi,

In such case, you need to be inside the app folder to execute the commands in such module.
Another way around from . is adding the -R (recursive) option.

Run walkmod add --help to see the options
