### ISSUE TITLE
LocalVarsShouldComplyWithNamingConvention not working for Parameters

### ISSUE THREAD

**Issue by subisueno** [walkmod/walkmod-core#70]
`package sonar.autofix;

public class LocalVarNaming {

	public void create(String corporate_base){
		System.out.println("corporate_base = "+corporate_base);
	}
}`
If I run  - `walkmod apply sonar:LocalVarsShouldComplyWithNamingConvention` causing compilation error.

`package sonar.autofix;

public class LocalVarNaming {

	public void create(String corporateAsecorporate_base	public void create(String corporate_base){
		System.out.println("corporate_base = "+corporate_base);
	}
}
`

**Comment by subisueno** [comment]
The Junit has been written by disabling Parameter modification - 
visitor.setRefactorParameters(false);

Then why the actual visitor is having set as true. If for parameters it is not working, can we not disable in the "LocalVarsShouldComplyWithNamingConvention.java" - 
private boolean refactorParameters = false;

Once it will be fixed, it can be enabled.

**Comment by rpau** [comment]
Hi, I have fixed that issue here:
https://github.com/walkmod/walkmod-javalang-plugin/commit/4ce376dce0b4cc0e958b3607394371104a6a87cf

I have just deployed a new version of the library. If you try again this afternoon, it should work.

**Comment by subisueno** [comment]
Still I am getting the issue. 3.0.2 is getting downloaded, not 3.0.3

**Comment by rpau** [comment]
Sorry, I uploaded the artefact, but I did not realize that I had not published the release. Now, I have tested it and works :)

**Comment by subisueno** [comment]
It is now renamed incorrectly from corporate_base to corporateAse. But, expected corporateBase.
