### ISSUE TITLE
Walkmod: Getting through a proxy

### ISSUE THREAD

**Issue by dan2218** [walkmod/walkmod-core#77]
Hi,

Having trouble getting through a proxy with Walkmod. I ran the following command.

walkmod apply - DconfigurationFile=ruleset.xml pmd 

It runs through fine but at the very end when it tries to get some additional google java stuff. It fails with a timeout. I believe this is due to a proxy. I posted an image of the message.

![image](https://user-images.githubusercontent.com/34276871/33612670-51e88af0-d9a0-11e7-9ad5-4afac0ad47e2.png)

I have tried configuring the proxy via environment variables WALKMOD_OPTS and also ANT_OPTS. I also configured the config/ivysetting.xml for the proxy as well. None of this worked.  Please let me know if you need any additional information. Any help would be great!

**Comment by rpau** [comment]
Thanks a lot for reporting so good this problem.

Sorry for the delayed response. It seems to me that the libraries it is trying to resolve belong to your project (guava and glassfish). Walkmod requires to get the sources compiled, and in your case is trying to do this through the maven API. Thus, this output belongs to maven :) and if it has run, it means that dependencies have been finally solved.
